# Generated by Django 3.0.7 on 2020-09-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='posts/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('Réalisations', 'réalisations'), ('Carrière', 'carrière'), ('Activités', 'activités')], max_length=15, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.Author')),
                ('likes', models.ManyToManyField(related_name='like', to='Model.Author')),
            ],
        ),
    ]
